#!/bin/bash

# Openbox Workstation
# Copyright (C) 2026 Surendra Beniwal
# SPDX-License-Identifier: GPL-3.0-or-later


if command -v dm-tool >/dev/null 2>&1; then
    dm-tool lock
elif command -v gnome-screensaver-command >/dev/null 2>&1; then
    gnome-screensaver-command --lock
elif command -v xdg-screensaver >/dev/null 2>&1; then
    xdg-screensaver activate
else
    notify-send "Lock Screen" "No supported screen locker found."
fi
